kind: pipeline
name: buster-nginx-mysql

steps:
  - name: build
    image: debian:${DEBIAN_VERSION}
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
    commands:
      - ./run_test.sh
      
matrix:
  DEBIAN_VERSION:
    - jessie
    - stretch
    - buster

---
kind: pipeline
name: debian-nginx-mysql

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-apache-mysql

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-nginx-sqlite

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-apache-sqlite

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: apache
      DATABASE: sqlite
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-nginx-mysql

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-apache-mysql

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-nginx-sqlite

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-apache-sqlite

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: apache
      DATABASE: sqlite
    commands:
      - ./run_test.sh

---
kind: pipeline
name: jessie-nginx-sqlite

steps:
  - name: build
    image: debian:jessie
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
    commands:
      - ./run_test.sh

---
kind: pipeline
name: jessie-pseudo-ovz

steps:
  - name: build
    image: debian:jessie
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
    commands:
      - mv /bin/uname /bin/original_uname
      - echo "echo 'Linux vps5785664248 2.6.32-042stab127.2 \#1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux'" > /bin/uname
      - chmod +x /bin/uname
      - ./run_test.sh