kind: pipeline
name: debian-buster-nginx-mysql
type: docker

steps:
  - name: build
    image: debian:buster
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
      DEBUG: true
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-buster-apache-mysql
type: docker

steps:
  - name: build
    image: debian:buster
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-stretch-nginx-mysql
type: docker

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-stretch-apache-mysql
type: docker

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-stretch-nginx-sqlite
type: docker

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-stretch-apache-sqlite
type: docker

steps:
  - name: build
    image: debian:stretch
    environment:
      WEB_SERVER: apache
      DATABASE: sqlite
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-focal-nginx-mysql
type: docker

steps:
  - name: build
    image: ubuntu:focal
    failure: ignore
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-focal-apache-mysql
type: docker

steps:
  - name: build
    image: ubuntu:focal
    failure: ignore
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-bionic-nginx-mysql
type: docker

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: nginx
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-bionic-apache-mysql
type: docker

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-bionic-nginx-sqlite
type: docker

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-bionic-apache-sqlite
type: docker

steps:
  - name: build
    image: ubuntu:bionic
    environment:
      WEB_SERVER: apache
      DATABASE: sqlite
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: ubuntu-xenial-nginx-mysql
type: docker

steps:
  - name: build
    image: ubuntu:xenial
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-jessie-nginx-sqlite
type: docker

steps:
  - name: build
    image: debian:jessie
    environment:
      WEB_SERVER: nginx
      DATABASE: sqlite
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - ./run_test.sh

---
kind: pipeline
name: debian-jessie-pseudo-ovz
type: docker

steps:
  - name: build
    image: debian:jessie
    environment:
      WEB_SERVER: apache
      DATABASE: mysql
      DAEMON_SETUP_TOKEN: test_auto_setup_token
    commands:
      - mv /bin/uname /bin/original_uname
      - echo "echo 'Linux vps5785664248 2.6.32-042stab127.2 \#1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux'" > /bin/uname
      - chmod +x /bin/uname
      - ./run_test.sh
